#!/bin/python
import configparser
import os
import sys

# Default overheat temperatures
hdd_overheat = 49
ssd_overheat = 60

# Define output file paths
yaml_mqtt_file = 'inc/mqtt/sensor/mqtt-sensor-storage-autogen.yaml'
yaml_template_file = 'inc/template/template-storage-autogen.yaml'

# --- Configuration Loading ---
config = configparser.ConfigParser()
try:
    config.read('sensors-storage-yaml-generator.ini', encoding='utf8')
except Exception as e:
    print(f"Error reading config file: {e}", file=sys.stderr)
    sys.exit(1)

# Override overheat temperatures from the config's default section if available
if 'DEFAULT' in config:
    if 'hdd_overheat' in config['DEFAULT']:
        try:
            hdd_overheat = int(config['DEFAULT']['hdd_overheat'])
        except ValueError:
            print("Warning: Invalid value for 'hdd_overheat' in config. Using default.", file=sys.stderr)

    if 'ssd_overheat' in config['DEFAULT']:
        try:
            ssd_overheat = int(config['DEFAULT']['ssd_overheat'])
        except ValueError:
            print("Warning: Invalid value for 'ssd_overheat' in config. Using default.", file=sys.stderr)

# --- File Existence Check and User Confirmation ---
if os.path.exists(yaml_mqtt_file):
    response = input(f"File {yaml_mqtt_file} already exists. Overwrite (y/N)? ").strip().lower()
    if response != 'y':
        sys.exit(0)

# Ensure directories exist
os.makedirs(os.path.dirname(yaml_mqtt_file), exist_ok=True)
os.makedirs(os.path.dirname(yaml_template_file), exist_ok=True)

# --- Open Output Files ---
try:
    yaml_mqtt_h = open(yaml_mqtt_file, 'w')
    yaml_template_h = open(yaml_template_file, 'w')
except IOError as e:
    print(f"Error opening file: {e}", file=sys.stderr)
    sys.exit(1)

separator = "\n#------------------------------------------------\n"
header = """#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: This file was generated automatically by sensors-storage-yaml-generator.py
# Do not edit manually!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: This file is included from the main configuration.yaml by the statement:
"""

print("Generating:")

yaml_mqtt_h.write(header + f"# mqtt:\n#   sensor: !include_dir_merge_list {yaml_mqtt_file}\n\n")
yaml_template_h.write(header + f"# template: !include_dir_merge_list {yaml_template_file}\n\n")
yaml_template_h.write("- sensor:\n")

# --- Generate YAML Content ---
for host in config.sections():
    if host == 'DEFAULT':
        continue

    print(f"\n{host}: ", end='')

    yaml_mqtt_h.write(separator + f"# host: {host}" + separator)
    yaml_template_h.write(separator + f"# host: {host}" + separator)

    if 'last_letter' not in config[host]:
        continue

    last_letter = config[host]['last_letter']

    # Iterate from 'a' up to the last_letter
    for i in range(ord('a'), ord(last_letter) + 1):
        drive_char = chr(i)
        print(f" {drive_char}", end='')

        d = 'sd' + drive_char

        # MQTT Sensor YAML
        yaml_mqtt_h.write(f"""
# {d}

- name: "{host}_sd{drive_char}_mqtt_state"
  state_topic: "sys/{host}/hw/storage/{d}/state"

- name: "{host}_{d}"
  state_topic: "sys/{host}/hw/storage/{d}/state"
  json_attributes_topic: "sys/{host}/hw/storage/{d}"

# json of smart attr. may be not present
- name: "{host}: {d} attributes"
  state_topic: "sys/{host}/hw/storage/{d}/attributes"
  json_attributes_topic: "sys/{host}/hw/storage/{d}/attributes"

- name: "{host}: {d} id"
  state_topic: "sys/{host}/hw/storage/{d}"
  value_template: "{{{{ state_attr( 'sensor.{host}_{d}', 'id' ) }}}}"

- name: "{host}: {d} model"
  state_topic: "sys/{host}/hw/storage/{d}"
  value_template: "{{{{ state_attr( 'sensor.{host}_{d}', 'model' ) }}}}"

- name: "{host}: {d} type"
  state_topic: "sys/{host}/hw/storage/{d}"
  value_template: "{{{{ state_attr( 'sensor.{host}_{d}', 'type' ) }}}}"

- name: "{host}: {d} temperature"
  state_topic: "sys/{host}/hw/storage/{d}/temperature"
  unit_of_measurement: °C
  device_class: temperature

# data freshness
- name: "{host}: {d} last update"
  state_topic: "sys/{host}/hw/storage/{d}/updated"
  json_attributes_topic: "sys/{host}/hw/storage/{d}/updated"
  value_template: "{{{{ value_json.timestamp }}}}"
""")
        # Note the indent is to be inside the for drive_letter loop
        # Home Assistant Template Sensor YAML
        # Escaping curly braces for Jinja2 templates ({{ and }})
        yaml_template_h.write(f"""
  - default_entity_id: sensor.{host}_{d}_freshness
    name: "{host}: {d} data freshness check"
    state: >-
      {{% set topic_u = 'sensor.{host}_{d}_last_update' %}}
      {{% if states( topic_u )|float(default=-1.0) == -1.0 %}}
        NO DATA!
      {{% elif as_timestamp(now()) - ( states( topic_u )|float ) > 1800 %}}
        OLD: {{{{ state_attr( topic_u, 'date' ) }}}}
      {{% else %}}
        OK
      {{% endif %}}

    icon: >-
      {{% set topic_u = 'sensor.{host}_{d}_last_update' %}}
      {{% if states( topic_u )|float(default=-1.0) == -1.0 %}}
        mdi:database-remove-outline
      {{% elif as_timestamp(now()) - ( states( topic_u )|float ) > 1800 %}}
        mdi:disc-alert
      {{% else %}}
        mdi:harddisk
      {{% endif %}}

  - default_entity_id: sensor.{host}_{d}_problems
    name: "{host}: {d} problems"
    state: >-
      {{% if states( 'sensor.{host}_{d}_freshness' ) != "OK" %}}
        {{{{ states( 'sensor.{host}_{d}_freshness' ) }}}}
      {{% else %}}
        {{% if states( 'sensor.{host}_{d}_mqtt_state' ) != 'OK' %}}
          {{{{ states( 'sensor.{host}_{d}_mqtt_state' ) }}}}
        {{% endif %}}
        {{% if states( 'sensor.{host}_{d}_temperature' )|float(default=-1.0) != -1.0 %}}
          {{% if states( 'sensor.{host}_{d}_type' ) == 'HDD' %}}
            {{% if states( 'sensor.{host}_{d}_temperature' )|float > {hdd_overheat} %}}
              OVERHEATING: {{{{ states( 'sensor.{host}_{d}_temperature' ) }}}}
              ( {{{{ states( 'sensor.{host}_{d}_id' ) }}}} )
            {{% endif %}}
          {{% else %}}
            {{% if states( 'sensor.{host}_{d}_temperature' )|float > {ssd_overheat} %}}
              OVERHEATING: {{{{ states( 'sensor.{host}_{d}_temperature' ) }}}}
              ( {{{{ states( 'sensor.{host}_{d}_id' ) }}}} )
            {{% endif %}}
          {{% endif %}}
        {{% endif %}}
      {{% endif %}}
""")

yaml_mqtt_h.close()
yaml_template_h.close()

print("\n")
