#!/bin/python
"""
This script queries Mikrotik router for various data and pushes it to the mqtt agent.
RouterOS V7+ required with REST API enabled.
Copyright by Andrej Pakhutin (pakhutin <at> gmail)
http://github.com/kadavris/monitoring
License: see accompanying LICENSE file in repo.
"""
from configparser import SectionProxy
import argparse
import configparser
import json
from kadpy.kmqtt import KMQTT
import os
import re
import requests
import signal
import sys
import time
from typing import Any, cast

#############################################################
# Common conversion helpers
time_to_seconds = {"w": 3600 * 24 * 7, "d": 3600 * 24, "h": 3600, "m": 60, "s": 1}
size_to_bytes = {"m": 1024 * 1024, "k": 1024}

# prototypes
mqtt_sender: KMQTT

def_config_path = '/etc/smarthome/monitoring/mikrotik/'
def_config_name = 'mikrotik2mqtt.ini'

#############################################################
def load_config(in_name: str) -> configparser.ConfigParser:
    """
    Will load configuration file, checking for problems beforehand
    :param in_name: path to config file
    :return: None
    """
    global ARGS, FULL_CONFIG

    conf_file_names = [in_name]

    if not os.path.isabs(in_name):  # adding fallback variants just in case
        conf_file_names.append(os.path.join(os.path.dirname(sys.argv[0]), in_name))
        conf_file_names.append(def_config_path + in_name)

    if ARGS.debug:
        print("+ Loading config:", in_name)

    FULL_CONFIG = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
    FULL_CONFIG.read(conf_file_names)

    if not FULL_CONFIG:
        print("ERROR: Can't read config from: ", ', '.join(conf_file_names), file=sys.stderr)
        sys.exit(1)

    return FULL_CONFIG


#############################################################
def handle_termination(signum=None, frame=None) -> None:
    """
    Will (safely) handle termination. Stopping sender agend on its rails.
    :param signum: NOT Used
    :param frame: NOT Used
    :return: None
    """
    if ARGS.debug:
        print("! signal caught. exiting.", file=sys.stderr)

    sys.exit(0)


########################################
def conf_vars_are_set(section: SectionProxy, names: list) -> bool:
    """
    Checks if a list of variables is present and set to true/on in the CONFIG

    :param section: .ini section reference
    :param names: list of config variables to check
    :return: True if present and set ON
    """
    for n in names:
        if n not in section or not section[n]:
            return False

    return True


#############################################################
class MikrotikQuery:
    # remap _some_ router's entity names to internal
    map_health = { "free-memory":"ram-free", "total-memory":"ram-total",
        "free-hdd-space":"hdd-free", "total-hdd-space":"hdd-total", "bad-blocks":"hdd-bad-blocks"}

    def __init__(self, global_ini: configparser.ConfigParser, name: str) -> None:
        """Creates an interface for calling a specific router device

        :param global_ini: ConfigParser instance
        :param name: .ini section name
        """
        self.name: str = name
        self.ini: configparser.SectionProxy = global_ini[name]
        self.url: str = self.ini['port'] + "://" + self.ini['ip'] + '/rest'

        self.last_error: int = 0
        # self.invalid: bool = False
        self.session: requests.Session = requests.Session()
        self.session.auth = (self.ini['user'], self.ini['password'])
        self.session.headers.update({'Content-Type': 'application/json'})
        self._ca = self.ini.get('cacert', False)

        self.traffic_stats: dict[str, int|float] = {}


    ####################################################
    def make_topic_path(self, /, *names, ini_key: str = '') -> str:
        """Constructs full topic name/path from the supplied components

        :param ini_key: str: if non-empty then our ini section will be queried for the value
        :param names: list of plain path components
        :return: str: Full path
        """
        if ini_key != "":
            if ini_key not in self.ini:
                raise KeyError(ini_key)

            return self.ini['topic_root'] + '/' + self.ini[ini_key] + '/' + '/'.join(names)
        else:
            return self.ini['topic_root'] + '/' + '/'.join(names)


    ####################################################
    def _query(self, cmd: str, parameters: None | dict[str, str] = None) -> \
            tuple[int, list[Any] | dict[str,Any]]:
        """Uses REST API to query router.

        :param cmd: str: command to send: /ip/filter/...
        :param parameters: dict: variadic parameters for the command, if needed
        :return: tuple: (<status code>, <data>)

        Use command in a native form: /x/y/z. Parameters are optional, depending on the command you use.
        Return value is a tuple where the 1st element is an integer status code
        and the 2nd is the data returned as is or None in case of error
        """
        global ARGS

        if ARGS.debug:
            print("D: -> query: '" + self.url + cmd + "'\n")

        if parameters:
            resp: requests.Response = self.session.post(self.url + cmd, data=json.dumps(parameters),
                                                    verify=self._ca)
        else:
            resp: requests.Response = self.session.post(self.url + cmd, verify=self._ca)

        if ARGS.debug:
            print("D: <- resp:  '" + resp.text + "'")

        try:
            data = resp.json()
            self.last_error = 0
            if type(data) is dict:
                if 'error' in data:
                    self.last_error = data['error']
            return self.last_error, data
        except requests.exceptions.JSONDecodeError:
            self.last_error = 400
            return 400, {"detail":"Invalid JSON","error":400,"message":"Bad Request"}
        except Exception as err:
            self.last_error = -1
            return -1, {"detail":str(err),"error":-1,"message":"whoopsie daisy"}


    ####################################################
    def get_hw_status(self) -> dict[str, Any]:
        """Collects hardware health related data and returns it as a dict with keys:
        "temperature", "voltage", "ram-free", "ram-total",
        "hdd-free", "hdd-total", "hdd-bad-blocks", "uptime", "cpu-load".
        Also, the "status" key will be "OK" in case everything is good or will contain diagnostics
        :return: dict: collected hardware health data
        """

        ret: dict[str, Any] = {}
        status: list[str] = []

        # temperature and voltage
        errcode, ans = self._query('/system/health/print')
        if errcode == 0:
            for item in cast(list[dict[str,Any]], ans):  # returns list of dict items
                ret[item["name"]] = float(item["value"])
        else:
            status.append("Query for health data: " + ans["detail"])

        errcode, ans = self._query('/system/resource/print')
        if errcode != 0:  # this is important, so we bail out immediately on error
            status.append("Query for system resources data: " + ans["detail"])
            return {"status": '; '.join(status)}

        ans = ans[0]  # returns list with a single dict inside
        for var in ans:
            val = ans[var]
            if var in MikrotikQuery.map_health:  # normalizing items names
                var = MikrotikQuery.map_health[var]

            if var == 'uptime':  # uptime: 8w2d21h37m11s
                ret[var] = val  # provide the original value as well
                t = 0
                # converting to seconds
                while m := re.match(r'((\d+)([wdhms]))', val):
                    n = int(m.group(2))
                    t += n * time_to_seconds[m.group(3)]
                    val = val[len(m.group(1)):]
                ret['uptime_sec'] = t

            elif var == 'ram-total' or var == 'ram-free' or var == 'hdd-free' or var == 'hdd-total':
                ret[var] = int(val)

            elif var == 'cpu-load':
                ret[var] = int(val)
                if ret[var] >= 95.0:
                    status.append('CPU hogged')

            elif var == 'hdd-bad-blocks':
                ret[var] = int(val)
                if ret[var] != 0.0:
                    status.append(val + '% of blocks on flash are bad')

        # Checking if memory and hdd are <=10% of respective totals
        if ret['ram-free'] <= ret['ram-total'] // 10:
            status.append('RAM is hogged')
        if ret['hdd-free'] <= ret['hdd-total'] // 10:
            status.append('HDD is full')

        if len(status) > 0:
            ret["status"] = '; '.join(status)
        else:
            ret["status"] = 'OK'

        return ret


    ####################################################
    def get_upgrades(self) -> str:
        """Will check if there are upgrades available and return text message as a status
        :return: str: 'OK' if no news
        """

        out: list[str] = []
        errcode, ans = self._query('/system/routerboard/print')

        if errcode != 0:
            return ans["detail"]

        ans = ans[0]

        if ans['current-firmware'] != ans['upgrade-firmware']:
            out.append("New firmware: " + ans["upgrade-firmware"])

        # ---------------------------------------
        errcode, ans = self._query('/system/package/update/print')

        if errcode != 0:
            return ans["detail"]

        ans = ans[0]

        if ans['installed-version'] != ans['latest-version']:
            out.append("Packages upgrade available: " + ans['latest-version'])

        if len(out) > 0:
            return '; '.join(out)

        return 'OK'


    ####################################################
    def process_stats(self, data: dict, prefix: str, entity: str, make_delta: bool) -> tuple[str,float]:
        """Processes new traffic stats package, adding deltas if requested.

        :param data: dict: The package
        :param prefix: unique prefix for saving stats from different sources of the same type
        :param entity: entity name in data package
        :param make_delta: True to compute difference with the last value
        :return: tuple[delta name, delta value] or ("",0)
        """
        if not make_delta:
            self.traffic_stats[prefix + entity] = data[entity]
            return "", 0.0

        val: int = int(data[entity])
        delta_val: float = 0.0
        is_speed: bool = entity.endswith('-byte') or entity.endswith('-packet')
        p_entity = prefix + entity

        if p_entity in self.traffic_stats:  # computing diff
            delta_val = float(val) - self.traffic_stats[p_entity]
            if delta_val < 0.0:  # stats reset on router?. just in case
                delta_val = 0.0

        # Let some deltas be in the form of speed (N/second)
        if is_speed:
            delta_val = round(delta_val / float(self.ini['report_interval']), 3)
            delta_suff = '-speed'
        else:
            delta_suff = '-delta'

        delta_name = entity + delta_suff
        self.traffic_stats[prefix + delta_name] = delta_val
        self.traffic_stats[prefix + entity] = val
        return delta_name, delta_val


    ####################################################
    def get_traffic(self, want_deltas: list[str]) -> dict[str,dict[str,Any]]:
        """Collects traffic stats and computes deltas if requested.

        :param want_deltas: list[str] list of metrics for which to compute delta values on output
        :return: {"interface name":{<traffic stats>}}
        """
        out = {}
        for interface in self.ini['get_traffic'].split():
            errcode, ans = self._query('/interface/print',
                              {"stats-detail":"", "from":interface})

            if errcode != 0:
                continue

            ans = ans[0]
            ak = list(ans.keys())
            for var in ak:
                if var in want_deltas:
                    dname, dval = self.process_stats(ans, interface, var, True)
                    ans[dname] = dval

            # determining the /state topic value
            problems = ''
            for problems_topic in ['link-downs-delta', 'tx-queue-drop-delta', 'rx-drop-delta', 'tx-drop-delta']:
                problems_key = interface + problems_topic
                if problems_key not in self.traffic_stats:
                    problems = problems + ' WARN: No data for ' + problems_key
                elif self.traffic_stats[problems_key] > 0:
                    problems = problems + ' ERRORS on ' + problems_key

            if problems != '':
                ans['status'] = problems
            else:
                ans['status'] = 'OK'

            out[interface] = ans

        return out


    ####################################################
    def get_firewall(self, filter_on: str = "", search: str = "") -> dict[str,Any]:
        """Will query device for firewall stats with possible filtering.
        Default filter is STATID: on comment's start

        :param filter_on: str: which stats item to filter on. optional.
        :param search: str: the search string to filter on. optional.
        :return: list of tuples: (<stat_name>, <bytes>, <packets>)
        """
        out = {}
        errcode, ans = self._query("/ip/firewall/filter/print")
        if errcode != 0:
            return []

        for item in cast(list[dict[str,Any]], ans):
            if filter_on != "":
                if filter_on not in item:
                    continue
                if search == "" or search in item[filter_on]:
                    out[item[".id"] + '-bytes'] = item["bytes"]
                    out[item[".id"] + '-packets'] = item["packets"]
                continue

            if search != "":
                for k in item.keys():
                    if type(item[k]) == str and search in item[k]:
                        out[item[".id"] + '-bytes'] = item["bytes"]
                        out[item[".id"] + '-packets'] = item["packets"]
                        continue
                continue

            # in this part we're getting only tagged items out
            if "comment" not in item:
                continue

            c = item["comment"].strip().split()
            if not c[0].startswith("STATID:"):
                continue
            sid = c[0][7:]

            for metric in ['bytes', 'packets']:
                metric_out_name = sid + '-' + metric
                out[metric_out_name] = int(item[metric])

                # computing deltas
                _, val = self.process_stats({metric_out_name:item[metric]}, "firewall",
                                               metric_out_name, True)
                out[metric_out_name + "-delta"] = val

        return out


# end of class MikrotikQuery


routers: list[MikrotikQuery] = []


####################################################
def post_system_status(dev: MikrotikQuery) -> str:
    """Retrieves general hardware status information like device temperature and RAM usage

    :return: empty string if no problems
    """
    ans = dev.get_hw_status()

    status: list[str] = []
    if ans["status"] != "OK":
        status += ans["status"]

    to_send: dict[str, Any] = {}

    for stat_name in ans.keys():
        if stat_name in ["temperature", "voltage"]:
            if conf_vars_are_set(dev.ini, ['get_' + stat_name, 'topic_' + stat_name]):
                if stat_name == "temperature" and int(ans[stat_name]) >= 50:
                    status.append("Overheating(>=50)")
                mqtt_sender.send_json_short(dev.make_topic_path(ini_key='topic_' + stat_name),
                                            str(ans[stat_name]))

        if stat_name == 'uptime':  # uptime: 8w2d21h37m11s
            to_send[stat_name] = ans[stat_name]
            t = 0  # converting to seconds

            val = ans[stat_name]
            while m := re.match(r'((\d+)([wdhms]))', val):
                n = int(m.group(2))
                t += n * time_to_seconds[m.group(3)]
                val = val[len(m.group(1)):]
            to_send['uptime_sec'] = t

        elif stat_name in ['ram-total', 'ram-free', 'hdd-free', 'hdd-total', 'hdd-bad-blocks', 'cpu-load']:
            to_send[stat_name] = ans[stat_name]

    mqtt_sender.send_json_long(dev.make_topic_path('system/resources'), json.dumps(to_send))

    if 'hdd-bad-blocks' in to_send and to_send['hdd-bad-blocks'] != 0.0:
        status.append(str(to_send['hdd-bad-blocks']) + '% of blocks on flash are bad')

    # Checking if memory and hdd are <=10% of total amount
    if to_send['ram-free'] <= to_send['ram-total'] / 10.0:
        status.append('RAM is hogged')

    if to_send['hdd-free'] <= to_send['hdd-total'] / 10.0:
        status.append('HDD is full')

    if to_send['cpu-load'] >= 95.0:
        status.append('CPU hogged')

    return '; '.join(status)


####################################################
def post_upgrades(dev: MikrotikQuery) -> None:
    """Will check if upgrades available and will post the news to the configured topic

    :return: None
    """

    if not conf_vars_are_set(dev.ini, ['topic_upgrades', 'get_updates']):
        return

    ans = dev.get_upgrades()

    mqtt_sender.send_json_short(dev.make_topic_path(ini_key='topic_upgrades'), ans)


####################################################
def post_traffic(dev: MikrotikQuery) -> None:
    """Goes through the list of interfaces from .ini and requests statistics for each of them

    :return: None
    """

    # Using traffic_stats cache will add computed deltas for these parameters to better show variations
    want_deltas = ['rx-byte', 'tx-byte', 'rx-error', 'tx-error',
                   'rx-drop', 'tx-drop', 'rx-packet', 'tx-packet',
                   'fp-rx-byte', 'fp-tx-byte', 'fp-rx-packet', 'fp-tx-packet',
                   'link-downs', 'tx-queue-drop']

    ans = dev.get_traffic(want_deltas)

    for interface in ans.keys():
        status: str = ans[interface]['status']
        del ans[interface]['status']  # we send it to separate topic
        mqtt_sender.send_json_short(dev.make_topic_path(interface.lower(), ini_key='topic_traffic'),
                                    json.dumps(ans[interface]))

        mqtt_sender.send_json_short(dev.make_topic_path(interface.lower() + '/state',
                                                        ini_key='topic_traffic'),
                           status)


####################################################
def post_firewall(dev: MikrotikQuery) -> None:
    """Starting point for firewall checks

    :return: None
    """

    msgs = {}
    if 'get_firewall_by_id' in dev.ini:
        msgs[dev.ini['get_firewall_by_id']] = json.dumps(dev.get_firewall())

    for topic in msgs:
        if msgs[topic].strip() == '':
            continue

        mqtt_sender.send_json_short(dev.make_topic_path(topic),
                           msgs[topic], retain=False)

        # for now just send a vanishing 'OK'
        mqtt_sender.send_json_short(dev.make_topic_path(topic + '/state'),
                                    'OK', retain=False)


####################################################
def poll_device(dev: MikrotikQuery) -> None:
    """Do all configured data retrievals for the single device.
    :return: None
    """
    status: list[str] = []  # functions will return text describing any problems or empty for none
    rc = post_system_status(dev)
    if rc:
        status.append(rc)

    if conf_vars_are_set(dev.ini, ['get_updates']):
        post_upgrades(dev)

    if conf_vars_are_set(dev.ini, ['get_traffic', 'topic_traffic']):
        post_traffic(dev)

    post_firewall(dev)

    mqtt_sender.send_json_short(dev.ini['topic_root'], ';'.join(status) if status else 'OK', retain=True)
    mqtt_sender.send_json_short(dev.make_topic_path('updated'), Dates_json, retain=True)


####################################################
# MAIN
global FULL_CONFIG

parser = argparse.ArgumentParser(
    description='Queries MikroTik router(s) for statistics data and pushes it to the mqtt agent. ' +
                'Copyright by Andrej Pakhutin (pakhutin <at> gmail). ' +
                'V2.0.1')
parser.add_argument('-c', '--config', dest='config_path', action='store',
                    default=def_config_path + def_config_name,
                    help='path to a non-default config file')
parser.add_argument('-d', '--debug', dest='debug', action='store_true', default=False,
                    help='debug mode')
parser.add_argument('-l', '--loop', dest='loop', action='store_true', default=False,
                    help='Loop forever, sleeping report_interval(see .ini) seconds between passes.')

ARGS = parser.parse_args()

CONFIG_DEFAULT = load_config(ARGS.config_path)['DEFAULT']

# mqtt sender script tend to hang up (why no SIGPIPE on stdin read?) if we exit hastily.
# Trying to avoid this.
signal.signal(signal.SIGINT, handle_termination)
signal.signal(signal.SIGTERM, handle_termination)

mqtt_sender = KMQTT(CONFIG_DEFAULT["sender"], True, ARGS.debug)

##################################
# set necessary defaults
if 'report_interval' not in CONFIG_DEFAULT:
    CONFIG_DEFAULT['report_interval'] = '60'

# will be used globally in misc topics posts to show last data times
Dates_json = ''

for router in FULL_CONFIG:
    if router == 'DEFAULT':
        continue

    if FULL_CONFIG[router].getboolean('disabled', False):
        continue

    routers.append(MikrotikQuery(FULL_CONFIG, router))

##################################
while True:  # main loop
    Dates_json = '{ "date":"' + time.ctime() + '", "timestamp":' + str(int(time.time())) + ' }'

    for router in routers:
        poll_device(router)

    if not ARGS.loop:
        break

    time.sleep(float(CONFIG_DEFAULT['report_interval']))

# Wrapping up
mqtt_sender.terminate()
