#!/usr/bin/env python3
"""
 This script produces reports on electrical power and push it into mqtt.
 repo is in github.com/kadavris.
 assumed topic structure:
     power
         <dev_id> - {"model":"...", "errors":"...", "attribute1":"..."...}
            state_topic... - one-line state message
            updated - JSON: { "date":"human-readable date", timestamp:UNIXTS }
"""
import argparse
import configparser
from configparser import ConfigParser, SectionProxy
import json
from kadpy.kmqtt import KMQTT
from kadpy.kpowerdevice import KPowerDevice
import os
import os.path
import re
import signal
import socket
import sys
import subprocess
import time
from typing import Any

# globals and prototypes to shut IDE up
DEFAULT_CONFIG_PATH = '/etc/smarthome/monitoring/'
DEFAULT_CONFIG_FILE = DEFAULT_CONFIG_PATH + 'mqtt-power.ini'
GLOBAL_CONFIG: ConfigParser = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
Sender: KMQTT
DEVICES: dict[str, KPowerDevice] = {}

#############################################################
def handle_termination(signum, frame) -> None:
    """
    Will (safely) handle termination. Stopping sender agent on its rails.
    :param signum: NOT USED
    :param frame: ALSO NOT USED
    :return: None
    """
    if ARGS.debug:
        print("! signal caught. exiting.", file=sys.stderr)

    if Sender:
        Sender.terminate()

    # todo: close logs and stats
    sys.exit(0)


#############################################################
def load_config(c_file: str) -> None:
    """
    Will load configuration file, checking for problems beforehand
    :param c_file: path to config file
    :return: parsed config section object
    """
    global ARGS, GLOBAL_CONFIG

    file = c_file

    if not os.path.exists(file):
        if '/' in file:
            print("! Can't open config: ", file, file=sys.stderr)
            sys.exit(1)

        file = DEFAULT_CONFIG_PATH + c_file

    if ARGS.debug:
        print("+ Loading config:", file)

    GLOBAL_CONFIG.read(file)


########################################
def update_vf_stats(dev_id: str, prefix: str, time_value: int, voltage: float, freq: float) -> None:
    """
    Will update stats[ device ] with per-minute, hourly or daily values depending on a prefix value.
    All keys in form prefix + 'string' must be in sync with outer function for values to be reported successfully
    :param dev_id: str: device path
    :param prefix: str: 'm'/'h'/'d' - time fraction unit
    :param time_value: int: time part value that we're accounting for
    :param voltage: float: as reported by device
    :param freq: float: frequency as reportde by device
    :return: None
    """
    global stats_vf

    ds = stats_vf[dev_id]
    if ds[prefix + 'start'] != time_value:  # new time period?
        # making old mean the 1st value of this period
        ds[prefix + 'samples'] = 1 if ds[prefix + '_v_mean'] > 0 else 0
        if voltage > 0.0:
            ds[prefix + 'samples'] += 1
        ds[prefix + 'v'] = ds[prefix + '_v_mean'] + int(voltage)
        ds[prefix + 'f'] = ds[prefix + '_f_mean'] + int(freq)
        ds[prefix + 'start'] = time_value

        if prefix == 'd':  # reset blackouts info. Later we may switch to 'last 24 hours'
            ds['bo_time'] = 0
            ds['blackouts'] = 0
            ds['in_bo'] = False
    else:  # same period
        if voltage > 0.0:  # don't account for blackouts from russian cultural bombings.
            ds[prefix + 'samples'] += 1
            ds[prefix + 'v'] += voltage
            ds[prefix + 'f'] += freq

    # Managing blackouts info
    if voltage > 0.0:
        ds['in_bo'] = False
    else:
        if prefix == 'd':  # update blackouts once per m/h/d calls series
            ds['bo_time'] += int(GLOBAL_CONFIG['power.' + dev_id]['sample_interval'])
            if not ds['in_bo']:
                ds['blackouts'] += 1
                ds['in_bo'] = True

    # updating mean values
    if ds[prefix + 'samples'] != 0:
        ds[prefix + '_v_mean'] = ds[prefix + 'v'] // ds[prefix + 'samples']
        ds[prefix + '_f_mean'] = ds[prefix + 'f'] // ds[prefix + 'samples']


########################################
def get_model_specific_config(dev_id: str, keyword: str, default: str = "") -> str:
    """
    Return the value of model-specific setting from config.
    :param dev_id: str. NUT's ID of UPS device
    :param keyword: str. Attribute/keyword name
    :param default: str. Default value to return if not found
    :return: str. The value
    """
    global GLOBAL_CONFIG

    return GLOBAL_CONFIG["power." + dev_id].get(keyword, default)


########################################
def device_init(dev_id: str) -> bool:
    """
    Prepares device data sourced from configuration file.
    :param dev_id: str: device ID
    :return: bool: success
    """
    global DEVICES, GLOBAL_CONFIG

    dev_sect_name = 'power.' + dev_id
    if dev_sect_name not in GLOBAL_CONFIG:
        print(f'ERROR: no device section {dev_sect_name} found in the config')
        return False

    kpd = DEVICES[dev_id] = KPowerDevice(dev_id, GLOBAL_CONFIG)

    if kpd.init_errors > 0:
        print(f'ERROR: device {dev_id} has errors setting up: ', kpd.collect_messages())
        return False

    if ARGS.debug:
        if kpd.init_warnings > 0:
            print(f'+ Device {dev_id} initialized with warnings:\n    ' + '\n    '.join(kpd.collect_messages()))
        else:
            print(f'+ Device {dev_id} initialized')

    return True


########################################
def get_data_from_upsc(dev_id: str) -> dict:
    """
    Collects data from upsc output for given device.
    :param dev_id:
    :return: dict("model":"manufacturer model", "data":dict(attribute:val))
    """
    global ARGS, DEVICES, stats_vf

    data: dict[str, Any] = {}
    to_return: dict[str, Any] = {
        "model": "", "errors": "",
        "data": data,  # attributes values will be here
    }

    # initializing the list of minimal attributes that we need for reports (note '.'s are replaced by '_'s)
    upsc_attributes_needed = [
        'device_mfr',  # manufacturer
        'device_model',
        'device_type',  # ups
        'ups_status',  # ups.status: OL/OB or whatever ups may want to report
    ]

    kpd = DEVICES[dev_id]
    # adding user-defined properties
    if kpd.one_to_one:
        for pair in kpd.one_to_one:
            oto_attr, oto_topic = pair.split(':')
            upsc_attributes_needed.append(oto_attr)

    if kpd.bulk_report:
        to_return['bulk_report'] = ' '.join(kpd.bulk_report)
        upsc_attributes_needed.extend( kpd.bulk_report )

    upsc_bin = ['upsc', dev_id]
    if 'upsc_binary' in GLOBAL_CONFIG['DEFAULT']:
        upsc_bin = GLOBAL_CONFIG.get('DEFAULT', 'upsc_binary').replace('$device', dev_id).split()

    upsc_proc = subprocess.Popen(upsc_bin,
                            stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                            stderr=(None if ARGS.debug else subprocess.DEVNULL), text=True)

    if upsc_proc.poll():
        if upsc_proc.returncode > 0:
            to_return["errors"] = '"upsc error":"ended with rc: ' + str(upsc_proc.returncode) + '"'
            print(to_return["errors"])
        return to_return

    out, err = upsc_proc.communicate()  # communicate() will return all output at once

    if err and (err != ''):
        to_return["errors"] = '"upsc error":"' + err + "'"
        print(to_return["errors"])
        return to_return

    for report_line in out.splitlines():
        # attribute?
        rm = re.match(r'([\w.]+):\s+(.+)', report_line)
        if not rm:
            continue

        attribute_name = rm.group(1).replace('.', '_')

        if attribute_name not in upsc_attributes_needed:
            continue

        data[attribute_name] = rm.group(2).strip()

    # do some stats
    try:
        t = time.localtime()

        v = float(data['input_voltage'])
        f = float(data.get('input_frequency', data.get('output_frequency', 0.0 )))

        if dev_id not in stats_vf:  # init
            stats_vf[dev_id] = {
                'blackouts': 0, 'bo_time': 0, 'in_bo': False,
                'mstart': 0, 'm_v_mean': 0, 'mv': 0.0,  # minute
                'mf': 0, 'm_f_mean': 0, 'msamples': 0,
                'hstart': 0, 'h_v_mean': 0, 'hv': 0.0,  # hour
                'hf': 0, 'h_f_mean': 0, 'hsamples': 0,
                'dstart': 0, 'd_v_mean': 0, 'dv': 0.0,  # day
                'df': 0, 'd_f_mean': 0, 'dsamples': 0
            }

        update_vf_stats(dev_id, 'm', t.tm_min, v, f)
        update_vf_stats(dev_id, 'h', t.tm_hour, v, f)
        update_vf_stats(dev_id, 'd', t.tm_mday, v, f)

        data['voltage_mean_minute'] = stats_vf[dev_id]['m_v_mean']
        data['frequency_mean_minute'] = stats_vf[dev_id]['m_f_mean']

        data['voltage_mean_hour'] = stats_vf[dev_id]['h_v_mean']
        data['frequency_mean_hour'] = stats_vf[dev_id]['h_f_mean']

        data['voltage_mean_day'] = stats_vf[dev_id]['d_v_mean']
        data['frequency_mean_day'] = stats_vf[dev_id]['d_f_mean']

        data['blackouts'] = stats_vf[dev_id]['blackouts']
        data['time_in_blackouts'] = stats_vf[dev_id]['bo_time']
    except Exception:
        pass

    # fill in specials:
    # device.mfr: EATON. Some UPS report empty string here
    if 'device_mfr' in data and data['device_mfr'] != "":
        to_return['model'] = data['device_mfr']
    else:
        to_return['model'] = get_model_specific_config(dev_id, ".mfr", "UNSPECIFIED MFR")

    if 'device_model' in data and data['device_model']:
        to_return['model'] += ' ' + data['device_model']
    else:
        to_return['model'] += ' ' + get_model_specific_config(dev_id, ".model", "")

    return to_return


########################################
def check_nut() -> bool:
    """
    Will analyze upsc output and send the data to MQTT.
    Default function to run on invocation of this script.
    :return: bool - False in case of trouble
    """
    global ARGS, DEVICES, Sender, stats_vf

    for dev_id in DEVICES:
        dev_conf = GLOBAL_CONFIG['power.' + dev_id]
        dev_topic = dev_conf['device_topic'].replace('$device', dev_id)

        if ARGS.debug:
            print('device:', dev_id, 'topic:', dev_topic)

        report_on_upsc = get_data_from_upsc(dev_id)
        repdata = report_on_upsc['data']

        kpd = DEVICES[dev_id]
        # run stat updates first, because it will compute some things we'll need here
        kpd.process_upsc_data( repdata )
        if kpd.next_stats_save < time.time():
            if kpd.stats_file_save():
                kpd.next_stats_save = time.time() + 600.0
            else:
                kpd.next_stats_save = time.time() + 3600.0  # in case of errors, postpone next save

        repdata['batteries'] = battrep = {}
        for battname in kpd.batteries.get_list():
            b = kpd.batteries[battname]
            h = b.get_battery_health()
            battrep[battname] = {
                'charge': b.charge,
                'health': h['status']
            }

        # WARNING! Past this point, upsc data will be replaced with normalized data!
        repdata['runtimes'] = kpd.get_battery_runtime()
        repdata['ups_load'] = kpd.commons.last_load

        if kpd.commons.calc_charge_data:
            rp = kpd.batteries.get_remaining_power()
            repdata['battery_charge'] = str(round(rp[1], 1))

        # we will count the configured checks to report if none were enabled actually
        checks_run = 0
        checks_with_errors = 0

        # this will be sent last and be updated by other analysis code on the way
        repdata['model'] = report_on_upsc['model']
        repdata['errors'] = report_on_upsc['errors']

        bulk_msg = json.dumps(repdata, sort_keys=True, indent=0)

        # --------------------------------
        if 'log_samples' in dev_conf:
            log_name = dev_conf['log_samples'].replace('$device', dev_id)
            try:
                time_str = time.strftime(r'%Y-%m-%d %H:%M:%S')

                line = ''
                if kpd.log_items:  # a subset of data requested
                    for ki in range(len(kpd.log_items)):
                        if kpd.log_items[ki] not in repdata:
                            line += time_str + ' WARNING! upsc does not provide item "' + kpd.log_items[ki] + '"\n'
                            kpd.log_items[ki] = None

                    line += time_str + ' { "date":"' + time_str + '"'

                    for li in kpd.log_items:
                        if li:
                            line += ', "' + li + '":"' + str(repdata[li]) + '"'

                    line += ' }\n'

                else:  # just log anything that we've got
                    line = time_str + bulk_msg.replace('\n', ' ') + '\n'

                open(log_name, mode='a').writelines(line)

            except Exception:
                del dev_conf['log_samples']
                print('! Error writing log file: ', log_name, ':',
                      sys.exc_info()[0], file=sys.stderr)
        # if 'log_samples' in config

        # is it time to post new data?
        next_rep = dev_id + '_next_report'

        if (next_rep in stats_vf) and stats_vf[next_rep] > time.time():  # too soon to report?
            continue

        stats_vf[next_rep] = time.time() + float(dev_conf['report_interval'])

        # quick post one-to-one data
        if kpd.one_to_one:
            for pair in kpd.one_to_one:
                oto_attr, oto_topic = pair.split(':')
                checks_run += 1

                if oto_attr in repdata:
                    msg = str(repdata[oto_attr])
                else:
                    if oto_attr in ['ups_alarm']:
                        msg = 'OK'
                    else:
                        msg = 'NO DATA'
                        checks_with_errors += 1

                Sender.send_json_short(dev_topic + '/' + oto_topic, msg, retain=True)

        # finally sending general status message
        if report_on_upsc['errors'] != '' or ('ups_status' not in repdata):
            msg = report_on_upsc['errors']
            checks_with_errors += 1
        else:
            msg = repdata['ups_status']

        checks_run += 1

        Sender.send_json_short(dev_topic + '/' + dev_conf['state_topic'], msg, retain=True)

        # sending time stats
        Sender.send_json_short(dev_topic + '/' + dev_conf['updated_topic'], Dates_json, retain=True)

        # doing bulk report message. we'll use 'mpublish' posting method, so no quoting is needed
        stop_word = '25@5h256h256H'
        bulk_msg = bulk_msg[:-1] + ', "checks run":' + str(checks_run) + \
            ', "checks with errors":' + str(checks_with_errors) + ' }'

        Sender.send_json_long(dev_topic, bulk_msg, retain=True, stop_word=stop_word)

    # end loop: for device in list
    return True


####################################################
# MAIN
parser = argparse.ArgumentParser(
    description='Collecting uninterruptible power device info and passing it to mqtt agent. V2.7.0.'
                ' Created by Andrej Pakhutin - pakhutin at gmail.'
    )
parser.add_argument('-c', '--config', dest='config_path', action='store', default=DEFAULT_CONFIG_FILE,
                    help='path to non-default config file')
parser.add_argument('-d', '--debug', dest='debug', action='store_true', default=False,
                    help='debug mode')
parser.add_argument('-l', '--loop', dest='loop', action='store', type=int, default=-1,
                    help='Loop forever, sleeping <int> seconds between passes. ' +
                         'If > 0 then overrides config "sample_interval" settings')
parser.add_argument('action', nargs='?', default='', help='non-default action name to run')

ARGS = parser.parse_args()

load_config(ARGS.config_path)
DEF_CONF: SectionProxy = GLOBAL_CONFIG['DEFAULT']

# mqtt sender script tend to hang up (why no SIGPIPE on stdin read?) if we exit hastily.
# Try to avoid this.
signal.signal(signal.SIGINT, handle_termination)
signal.signal(signal.SIGTERM, handle_termination)

hba = socket.gethostbyaddr(socket.gethostname())
hostname = re.sub(r'\..+', '', hba[0])

Sender = KMQTT(DEF_CONF['sender'], True, ARGS.debug)

if ARGS.debug:
    if not Sender:
        sys.exit(1)

Dates_json = ''  # will hold reusable date/timestamp JSON
action_list = []  # action list to run through
stats_vf = {}  # statistics about voltage and frequency

##################################
# set necessary defaults
if 'sample_interval' not in DEF_CONF:
    if ARGS.loop > 0:
        DEF_CONF['sample_interval'] = str(ARGS.loop)
    else:
        DEF_CONF['sample_interval'] = '60'  # seconds

if 'report_interval' not in DEF_CONF:
    DEF_CONF['report_interval'] = DEF_CONF['sample_interval']

##################################
# Which functions should we run. default is check_nut
if ARGS.action != '':
    action_list.append(ARGS.action)
else:
    action_list = [check_nut]

problems = False
# pre-initializing device data for NUT interface
if check_nut in action_list:
    if 'devices' in DEF_CONF:
        dev_list = DEF_CONF['devices'].split()
    else:
        if ARGS.debug:
            print('requesting the list of devices from upsc')

        upsc = subprocess.Popen(['upsc', '-l'],
                                stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                                stderr=(None if ARGS.debug else subprocess.DEVNULL), text=True)
        dev_list = upsc.communicate()[0].splitlines()

    for device in dev_list:
        if not device_init(device):
            problems = True

while not problems:  # main loop
    Dates_json = '{ "date":"' + time.ctime() + '", "timestamp":' + str(int(time.time())) + ' }'
    Dates_json = Dates_json.replace(r'"', r'\"')

    for func in action_list:
        if not func():
            problems = True
            break

    if problems:
        break

    if int(DEF_CONF['sample_interval']) <= 0:
        break

    time.sleep(int(DEF_CONF['sample_interval']))

if problems:
    print("! Exitting due to critical problems")

# end of the main loop - finalizing
Sender.terminate()
